### Instructions

* Sign up for the free course on Educative, __Learn Python 3 From Scratch__
* https://www.educative.io/courses/learn-python-3-from-scratch
* Complete the programming exercises below as you go through the course.
* Delete or comment out the line of code in each cell which says `raise NotImplementedError()` and replace it with your own.

# Educative - Data Structures

https://www.educative.io/courses/learn-python-3-from-scratch/R8XkWmQNj8R

### Exercises

Write your answers as comments in the cell below.

* What is the definition of a data structure in Python?

In [ ]:

# YOUR CODE HERE
# A data structure is a way of storing and organizing data according to a certain format or structure.

Write code in the cell below.

* Create a list named `new_list`.
* Make sure your list includes the following members: a string, an integer, a float, a boolean, another list.
* Print your list.
* Print the second item in your list.
* Print the second item in your nested list.

In [20]:

# YOUR CODE HERE
new_list = ["vartika","Bisariya",35, 5.6, True, ["nested", "list", "learning"]]
print (new_list)
print (new_list [2])
print (new_list[5][2])


['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning']]
35
learning


Write code in the cell below.

* Create a list named `second_list`.
* Make sure your list includes the following members: a string, an integer, a float, a boolean, another list.
* Print your list `new_list`.
* Print your list `second_list`.
* Create a list called `merged_list` which combines `new_list` and `second_list`.
* Print `merged_list`.

In [29]:

# YOUR CODE HERE
new_list = ["vartika","Bisariya",35, 5.6, True, ["nested", "list", "learning"]]
second_list = ["eat",30, 4.654, True, ["pizza", 7]]
print (new_list)

print (second_list)

merged_list = new_list + second_list
print (merged_list)


['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning']]
['eat', 30, 4.654, True, ['pizza', 7]]
['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 'eat', 30, 4.654, True, ['pizza', 7]]


Write code in the cell below.

* Use the extend() property to add `new_list` to the end of `merged_list`.
* Use the append() property to add the number 5 to the end of `merged_list`.
* Use the insert() property to add the word `first` to the beginning of `merged_list`.
* Print `merged_list`.

In [30]:

# YOUR CODE HERE
merged_list.extend (new_list)
print (merged_list)

merged_list.append(5)
print (merged_list)

merged_list.insert(0,"first")
print (merged_list)


['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 'eat', 30, 4.654, True, ['pizza', 7], 'vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning']]
['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 'eat', 30, 4.654, True, ['pizza', 7], 'vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 5]
['first', 'vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 'eat', 30, 4.654, True, ['pizza', 7], 'vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 5]


Write code in the cell below.

* Use the pop() operation to remove the last item from `merged_list`.
* Use the remove() method to remove the word `first`.
* Print `merged_list`.
* Print the index for the float value in `merged_list`.
* Verify the word `first` was removed from the list using the `not in` operator and printing the result.

In [31]:

# YOUR CODE HERE
last_item = merged_list.pop()
print (last_item)

merged_list.remove("first")
print (merged_list)

print(merged_list.index(5.6)) 

print ("first" not in merged_list)


5
['vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning'], 'eat', 30, 4.654, True, ['pizza', 7], 'vartika', 'Bisariya', 35, 5.6, True, ['nested', 'list', 'learning']]
3
True


Write code in the cell below.

* Sort `num_list` using the sort() method and print the result.

In [32]:
num_list = [20, 40, 10, 50.4, 30, 100, 5]

# YOUR CODE HERE
num_list.sort()
print(num_list)


[5, 10, 20, 30, 40, 50.4, 100]


Write code in the cell below.

* Create a new list `nums_double` whose values are the twice the values of the existing `nums` list using a list comprehension.
* Create a new list `nums_double_cond` whose values are the twice the values of the existing `nums` list using a list comprehension adding the condition that only elements divisible by 4 are included.
* Print `nums`, `nums_double`, `nums_double_cond` on separate lines.

In [33]:
nums = [10, 20, 30, 40, 50]

# YOUR CODE HERE
nums_double = []
nums_double_cond = []

for n in nums:
    nums_double.append(n * 2)
    
    nums_double_cond = [n * 2 for n in nums if n % 4 == 0]
    

print(nums)
print(nums_double)
print (nums_double_cond)


[10, 20, 30, 40, 50]
[20, 40, 60, 80, 100]
[40, 80]


Write code in the cell below.

* Create a new tuple named `cities` which includes the cities `London`, `Paris`, `Los Angeles`, and `Tokyo`.
* Print the index value for `Tokyo`.

In [41]:

# YOUR CODE HERE
cities = ("London", "Paris", "Los Angeles", "Tokyo")

print(cities)
print(cities.index("Tokyo")) 






('London', 'Paris', 'Los Angeles', 'Tokyo')
3


Write your answer as a comment in the cell below.

* What is the main difference between a list and a tuple?

In [ ]:

# YOUR CODE HERE
#Tuple is immutable and List is mutable.

Write code in the cell below.

* Create an empty dictionary called `empty_dict`.
* Print `empty_dict`.
* Create a dictionary called `phone_book` which includes the key:value pairs - `Batman`:`468426, `Cersei`:`237734`, `Ghostbusters`:`44678`.
* Pring `phone_book`.

In [42]:

# YOUR CODE HERE
empty_dict = {}  # Empty dictionary
print(empty_dict)

phone_book = {"Batman": 468426,
              "Cersei": 237734,
              "Ghostbusters": 44678}
print(phone_book)

{}
{'Batman': 468426, 'Cersei': 237734, 'Ghostbusters': 44678}


Write code in the cell below.

* Accomplish the tasks below using the dict() constructor.
* Create an empty dictionary called `empty_dict`.
* Print `empty_dict`.
* Create a dictionary called `phone_book` which includes the key:value pairs - `Batman`:`468426, `Cersei`:`237734`, `Ghostbusters`:`44678`.
* Pring `phone_book`.

In [43]:

# YOUR CODE HERE
empty_dict = dict()  # Empty dictionary
print(empty_dict)

phone_book = dict(Batman=468426, Cersei=237734, Ghostbusters=44678)

print(phone_book)

{}
{'Batman': 468426, 'Cersei': 237734, 'Ghostbusters': 44678}


Write code in the cell below.

* Print the number for `Cersei` by referencing the key.
* Print the number for `Ghostbusters` using the get() method.

In [44]:

# YOUR CODE HERE
hone_book = {"Batman": 468426,
              "Cersei": 237734,
              "Ghostbusters": 44678}
print(phone_book["Cersei"])
print(phone_book.get("Ghostbusters"))


237734
44678


Write code in the cell below.

* Add the number `46394` for `Godzilla` to `phone_book`.
* Print `phone_book`.
* Update the number for `Godzilla` to `9000`.
* Print `phone_book`.
* Delete the entry for `Batman` from `phone_book`
* Print `phone_book`.
* Add the contents of `second_phone_book` to `phone_book` using the update() operation.
* Print `phone_book`.

In [45]:
second_phone_book = {"Catwoman": 67423, "Jaime": 237734, "Godzilla": 37623}

# YOUR CODE HERE
phone_book = {"Batman": 468426,
              "Cersei": 237734,
              "Ghostbusters": 44678}

phone_book["Godzilla"] = 46394  
print(phone_book)

phone_book["Godzilla"] = 9000 
print(phone_book)

del phone_book["Batman"]
print(phone_book)

phone_book.update(second_phone_book)
print(phone_book)


{'Batman': 468426, 'Cersei': 237734, 'Ghostbusters': 44678, 'Godzilla': 46394}
{'Batman': 468426, 'Cersei': 237734, 'Ghostbusters': 44678, 'Godzilla': 9000}
{'Cersei': 237734, 'Ghostbusters': 44678, 'Godzilla': 9000}
{'Cersei': 237734, 'Ghostbusters': 44678, 'Godzilla': 37623, 'Catwoman': 67423, 'Jaime': 237734}


Write code in the cell below.

* Create a set called `random_set` containing the following items: `"Educative", 1408, 3.142, (True, False)`.
* Print `random_set`.
* Create an empty set called `empty_set` using the set() constructor.
* Print `empty_set`.
* Add `1` to `empty_set`.
* Print `empty_set`.
* Add the list `[2, 3, 4, 5, 6]` to `empty_set`.
* Print `empty_set`.

In [46]:

# YOUR CODE HERE
random_set = {"Educative", 1408, 3.142,
              (True, False)}
print(random_set)

empty_set = set()
print(empty_set)

empty_set.add(1)
print(empty_set)

empty_set.update([2, 3, 4, 5, 6])
print(empty_set)


{1408, 'Educative', 3.142, (True, False)}
set()
{1}
{1, 2, 3, 4, 5, 6}


Write code in the cell below.

* Find the union of `set_A` and `set_B` and print the results.

In [47]:
set_A = {1, 2, 3, 4}
set_B = {'a', 'b', 'c', 'd'}

# YOUR CODE HERE
print(set_A | set_B)
print(set_A.union(set_B))
print(set_B.union(set_A))

{1, 2, 3, 4, 'c', 'a', 'b', 'd'}
{1, 2, 3, 4, 'c', 'a', 'b', 'd'}
{'c', 1, 2, 'a', 3, 4, 'b', 'd'}


Write code in the cell below.

* Find the intersection of `set_A` and `set_B` and print the results.

In [49]:
set_A = {1, 2, 3, 4}
set_B = {'a', 'b', 'c', 'd'}

# YOUR CODE HERE

print(set_A & set_B)
print(set_A.intersection(set_B))
print(set_B.intersection(set_A))


set()
set()
set()


Write code in the cell below.

* Find the members of `set_A` that are not included in `set_B` and print the results.
* Find the members of `set_B` that are not included in `set_A` and print the results.

In [50]:
set_A = {1, 2, 3, 4}
set_B = {2, 8, 4, 16}

# YOUR CODE HERE

print(set_A - set_B)
print(set_A.difference(set_B))

print(set_B - set_A)
print(set_B.difference(set_A))

{1, 3}
{1, 3}
{8, 16}
{8, 16}


Write code in the cell below.

* Convert the following data structures into a list and print the result for each conversion.

In [51]:
star_wars_tup = ("Anakin", "Darth Vader", 1000)
print(star_wars_tup)
star_wars_set = {"Anakin", "Darth Vader", 1000}
print(star_wars_set)
star_wars_dict = {1: "Anakin", 2: "Darth Vader", 3: 1000}
print(star_wars_dict)

# YOUR CODE HERE

star_wars_list = list(star_wars_tup) 
print(star_wars_list)

star_wars_list = list(star_wars_set)  
print(star_wars_list)

star_wars_list = list(star_wars_dict)  
print(star_wars_list)


('Anakin', 'Darth Vader', 1000)
{1000, 'Darth Vader', 'Anakin'}
{1: 'Anakin', 2: 'Darth Vader', 3: 1000}
['Anakin', 'Darth Vader', 1000]
[1000, 'Darth Vader', 'Anakin']
[1, 2, 3]


Write code in the cell below.

* Convert the following data structures into a tuple and print the result for each conversion.

In [52]:
star_wars_list = ["Anakin", "Darth Vader", 1000]
print(star_wars_list)
star_wars_set = {"Anakin", "Darth Vader", 1000}
print(star_wars_set)
star_wars_dict = {1: "Anakin", 2: "Darth Vader", 3: 1000}
print(star_wars_dict)

# YOUR CODE HERE
tar_wars_tup = tuple(star_wars_list)  
print(star_wars_tup)

star_wars_tup = tuple(star_wars_set) 
print(star_wars_tup)

star_wars_tup = tuple(star_wars_dict)  
print(star_wars_tup)

['Anakin', 'Darth Vader', 1000]
{1000, 'Darth Vader', 'Anakin'}
{1: 'Anakin', 2: 'Darth Vader', 3: 1000}
('Anakin', 'Darth Vader', 1000)
(1000, 'Darth Vader', 'Anakin')
(1, 2, 3)


Write code in the cell below.

* Convert the following data structures into a set and print the result for each conversion.

In [53]:
star_wars_list = ["Anakin", "Darth Vader", 1000]
print(star_wars_list)
star_wars_tup = ("Anakin", "Darth Vader", 1000)
print(star_wars_tup)
star_wars_dict = {1: "Anakin", 2: "Darth Vader", 3: 1000}
print(star_wars_dict)

# YOUR CODE HERE
star_wars_set = set(star_wars_list)  
print(star_wars_set)

star_wars_set = set(star_wars_tup)  
print(star_wars_set)

star_wars_set = set(star_wars_dict)  
print(star_wars_set)


['Anakin', 'Darth Vader', 1000]
('Anakin', 'Darth Vader', 1000)
{1: 'Anakin', 2: 'Darth Vader', 3: 1000}
{1000, 'Darth Vader', 'Anakin'}
{1000, 'Darth Vader', 'Anakin'}
{1, 2, 3}


Write code in the cell below.

* Convert the following data structures into a dictionary and print the result for each conversion.

In [54]:
star_wars_list = [[1,"Anakin"], [2,"Darth Vader"], [3, 1000]]
print (star_wars_list)
star_wars_tup = ((1, "Anakin"), (2, "Darth Vader"), (3, 1000))
print (star_wars_tup)
star_wars_set = {(1, "Anakin"), (2, "Darth Vader"), (3, 1000)}
print (star_wars_set)

# YOUR CODE HERE

star_wars_dict = dict(star_wars_list) 
print(star_wars_dict)

star_wars_dict = dict(star_wars_tup) 
print(star_wars_dict)

star_wars_dict = dict(star_wars_set) 
print(star_wars_dict)

[[1, 'Anakin'], [2, 'Darth Vader'], [3, 1000]]
((1, 'Anakin'), (2, 'Darth Vader'), (3, 1000))
{(2, 'Darth Vader'), (1, 'Anakin'), (3, 1000)}
{1: 'Anakin', 2: 'Darth Vader', 3: 1000}
{1: 'Anakin', 2: 'Darth Vader', 3: 1000}
{2: 'Darth Vader', 1: 'Anakin', 3: 1000}
